apiVersion: apps/v1
kind: Deployment
metadata:
    name: docker-users
    labels:
        app: docker-users
spec:
    replicas: {{ .Values.replicaCount}}
    selector:
        matchLabels:
            app: docker-users
    template:
        metadata:
            name: docker-users
            labels:
                app: docker-users
        spec:
            containers:
                - name: docker-users
                  image: {{ .Values.image.repository }}
