apiVersion: v1
kind: ConfigMap
metadata:
   name: mysql-initdb-configmap
data:
   initdb.sql:
        CREATE DATABASE mydb;
        use mydb;        
        create table users(
        id int AUTO_INCREMENT PRIMARY KEY,
        name varchar(20),
        salary int,
        team_name varchar(20)         
        );