apiVersion: v1
kind: Service
metadata:
  name: docker-mysql
  labels:
     app: docker-mysql
spec:
  selector:
       app: docker-mysql
  type: {{ .Values.dbservice.type }}
  ports:
    - port: {{ .Values.dbservice.port }}
      targetPort: 3306
      nodePort: 30287 
