apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-users.fullname" . }}
  labels:
    {{- include "docker-users.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8086
      protocol: TCP
      name: http
  selector:
    {{- include "docker-users.selectorLabels" . | nindent 4 }}
