apiVersion: v1
kind: Service
metadata:
  name: docker-users
  labels:
      app: docker-users
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8086
      protocol: TCP
      name: http
  selector:
      app: docker-users
