apiVersion: app.example.com/v1alpha1
kind: App
metadata:
  name: app-sample
spec:
  # Default values copied from <project_dir>/helm-charts/app/values.yaml
  affinity: {}
  autoscaling:
    enabled: false
    maxReplicas: 100
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  fullnameOverride: ""
  image:
    repository: 750713/docker-users:latest
    pullPolicy: Always
  dbimage:
    repository: mysql
    pullPolicy: IfNotPresent
    
  secret:
    type: Opaque  
    
  imagePullSecrets: []
  ingress:
    annotations: {}
    enabled: false
    hosts:
    - host: chart-example.local
      paths: []
    tls: []
  nameOverride: ""
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  replicaCount: 1
  resources: {}
  securityContext: {}
  service:
    port: 8086
    type: NodePort
  dbservice:
    port: 3306
    type: NodePort  
  serviceAccount:
    annotations: {}
    create: true
    name: ""
  tolerations: []
  
  
